### PR TITLE
[WIP] Support of "Project Rome"

### PR DESCRIPTION
**Pull request by jlnostr**
> Most people have multiple devices, and often begin an activity on one device and finish it on another. To accommodate this, apps need to span devices and platforms.
> <cite>[Source (MSDN).](https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/connected-apps-and-devices)</cite>

I think this could be quite useful when it comes to reading an article. Users could simply close the app on the desktop and continue reading just by picking up their phone.

I made a quick draft of how the user interface could look like on the phone:
image

This feature would drop the current "sync" feature. The current implementation isn't neither realtime nor reliable, "Project Rome" would fill this gap.

### CODE REVIEW

**Comment by tcitworld** [comment]
Me gusta ! Really want to make this synchable through the API too !

**Comment by jlnostr** [comment]
Current status: I love this idea, but it lacks one point. The synchronisation can only be executed, if both devices are running. What shouldn't be a problem, if you're switching from the PC to the phone, might be an issue otherwise, because your PC isn't always turned on. There are three possible solutions for this issue:

1. Run a background task and send the message again if it failed before (can only execute every 15 minutes)
2. Rely on an external server (running on Microsoft Azure), which will then push the message if the PC was started (instant reaction, but I don't know anything about the costs, need to look into)
3. Sync last item id and the reading progress with the wallabag API (not implemented yet, at least not the last read item, see https://github.com/wallabag/wallabag/pull/2644)

The problems of solution 2 and solution 3 is that both require a working internet connection, option 1 also works if both devices are offline and 'only' in the same network.

**Comment by tcitworld** [comment]
Option 3 seems the best to me. Please open an issue about retrieving the last read item through the API to see if it's doable.

**Comment by jlnostr** [comment]
Closed to the above issues. Will wait until the API supports the sync of the reading progress.

**Comment by tcitworld** [comment]
Ref https://github.com/wallabag/wallabag/pull/2644 (please bear with me)

**Pull request closed without merging**
