### PR TITLE
Improved search & filter functionality

### PR DESCRIPTION
**Pull request by jlnostr**

### CODE REVIEW

**Comment by tcitworld** [comment]
Please update the app on the store and make my day. :) <3

**Comment by jlnostr** [comment]
That was my plan for today :)

**Comment by jlnostr** [comment]
Sadly, a bug is preventing the update. But I'm tired, so I'll look into the issue after some sleep :(

**Comment by tcitworld** [comment]
No worries. Good night. :)

**Comment by jlnostr** [comment]
Update published :)
*(unfortunately, it won't come with the background task, as this is causing the error)*

**Comment by tcitworld** [comment]
Nice !

**Pull request merged**
