### PR TITLE
Optimize UX and UI for the filter panel

### PR DESCRIPTION
**Pull request by jlnostr**
At the moment, the filter panel is neither functional nor beautiful/consistent. The goal of this PR is to improve both UI and UX.

Screenshot of the current implementation:
Screenshot

### CODE REVIEW

**Comment by jlnostr** [comment]
The current draft looks like the following:
image

And this way if you're hovering one of the **left** symbols:
image

I'm not sure about the style. Because of consistency reasons I think I need to add the same behaviour to the ascending/descending buttons (can they even identified as these?) on the right as well.
And a combobox just for two items is stupid, isn't it?

What do you think, @wallabag/wallabag-contributors?

**Comment by tcitworld** [comment]
As far as I can see, this is good like you present it.

Could you do screenshot in english next time so that everybody is certain of what each label means ?

**Comment by jlnostr** [comment]
Yeah, that's what I saw as well after I published the comment :D

**Comment by j0k3r** [comment]
It looks good to me.
Hovering the calendar will move the reading time icon to the right?

**Comment by jlnostr** [comment]
@tcitworld Updated the first screenshot.
@j0k3r  Yep. 

image

**Comment by Strubbl** [comment]
Is it possible to cross-compile that app for Linux with mono? Or are the dependencies to Windows too tight?

**Comment by jlnostr** [comment]
Nope, that's not possible. This app is made for Windows 10 and uses all of it's API features. If it would be a classic desktop application built with WinForms, it could be ported to Linux using Mono easily.

**Comment by tcitworld** [comment]
Well, you never know, since they seem to outsource everything these days.

**Comment by jlnostr** [comment]
While experimenting with the first solution, I also tried the ComboBox for another time. And this is the result, way more consistent than the first solution with floating buttons. Opinions?

image

**Comment by tcitworld** [comment]
Still have a small preference for the first one since it's faster to use.

**Comment by jlnostr** [comment]
Normal:
image

When hovering:
image

The best of two worlds, @tcitworld?

**Comment by jlnostr** [comment]
So, the panel is almost finished. There's just one thing I'm struggling with at the moment: the position.

## Option 1
**Position**: At the top right corner **after** opening the search (which is open by default on desktop, hidden behind a *magnifier* button on mobile) (took the old screenshot from my first post).
option1

**Advantages:**
- Easy to reach on desktop
- contains all filter options, item type not separated

**Disadvantages:**
- Hard to reach on mobile (two taps required, first to open the search, second to open the filter)

## Option 2
**Position**: At the bottom right corner with a button.
option2

**Advantages:**
- easy to reach on mobile and desktop
- swiping allows easy switch between item types

**Disadvantages:**
- more memory allocated, because the system now needs to display three seperate lists with items

## Option 3
**Position**: At the top left corner.
image

Option 4: Using a pivot.

Option 5: Using a floating header.
image

**Comment by jlnostr** [comment]
ping @wallabag/core

**Comment by nicosomb** [comment]
Option 2 👍

**Comment by tcitworld** [comment]
Slight preference for option 4, then option 2 as well.

**Comment by j0k3r** [comment]
Option 2 too

**Comment by jlnostr** [comment]
Thanks for the responses, option 2 is going to be implemented :)

**Comment by jlnostr** [comment]
Finished 😄 
image

**Comment by nicosomb** [comment]
🎉

**Pull request merged**
