### PR TITLE
[v2] Update HTML template

### PR DESCRIPTION
**Pull request by jlnostr**
Because @tcitworld wished it (see #52), I implemented tags on the article view. The current draft looks like this: 
image

I'm unsure if the tags should have an colored background like on the wallabag page. What do you think, @tcitworld?

### CODE REVIEW

**Comment by jlnostr** [comment]
Another draft would display the tags next to the date.
image

**Comment by tcitworld** [comment]
I would be inclined to choose the second variant, but what if there are many tags (over 5) ?

**Comment by jlnostr** [comment]
image
Like that.

**Comment by nicosomb** [comment]
Not bad!
Le 22 mars 2016 17:56, Julian Oster <notifications@github.com> a écrit :
Like that.

**Comment by tcitworld** [comment]
Yeah, i still think you should have some kind of background on the tags to distinguish them.

**Comment by jlnostr** [comment]
Light mode:
image

Dark mode:
image

Now I only need to find a way to update the HTML as well when I'm changing the tags over the native UI :D

**Comment by tcitworld** [comment]
Like it !

About changing the tags, I guess you can do this with JavaScript (you may also have to use js when bringing annotations. ;-) )

**Comment by jlnostr** [comment]
I'm already using JS in some way, but I think I'll ask Mr. StackOverflow another time to find a way :D

**Pull request merged**
