### PR TITLE
Update item template

### PR DESCRIPTION
**Pull request by jlnostr**
### Old

image
image

### New
image
image

And with tags:
image

What do you think @wallabag/core?

### CODE REVIEW

**Comment by j0k3r** [comment]
This is great!
Could this be a good idea to display the first XX words of the content ?

**Comment by jlnostr** [comment]
Thought about it. To reduce the clutter on small devices I would it only display while hovering the item. Another plan is to let the items having different sizes. Some would use two columns and some two rows. The additional space then can be used for a quick preview. I've got the inspiration from the preinstalled "news" app, screenshot is below.

image

**Comment by tcitworld** [comment]
I also like the idea of having optimal sizes for items like the news app does.

**Comment by jlnostr** [comment]
Current draft:
image

Every item will display the text as long as there's no image or the image hasn't been loaded yet.
image

**Comment by tcitworld** [comment]
Both are great. Can we have both ? :open_mouth:

**Comment by vainamov** [comment]
What would happen in draft 2, when there're no images or the images haven't been loaded yet?

**Comment by jlnostr** [comment]
@vainamov The same thing as in draft 1. The preview text will be shown instead.
@tcitworld Theoretically this should be possible. I'll have a look :)

**Comment by vainamov** [comment]
If so, I would follow @tcitworld and also prefer are mix of both.

**Comment by jlnostr** [comment]
Simple:
Simple
Extended, but without multiple rows:
extended1
Extended, with multiple rows:
extended2
And settings to change the template and the usage of multiple rows:
image

**Pull request merged**
