### PR TITLE
Support for wallabag v2

### PR DESCRIPTION
**Pull request by jlnostr**
I'll leave this PR open until wallabag v2 is released.
The app is almost ready-to-use and the following commits are just for polishment and bug fixing.

Don't worry, I have enough ideas for features, but they'll come later :)

### CODE REVIEW

**Comment by jlnostr** [comment]
Deprecated. Will release the source code of the new version soon.

**Comment by jlnostr** [comment]
And it's up on GitHub. This project can be deleted, the new one (https://github.com/jlnostr/wallabag-windows-app) is the replacement. Would be nice if it could be moved to the wallabag group :)

// ping @tcitworld @nicosomb

**Comment by nicosomb** [comment]
Good news. 
But I don't have permissions to do it, it's your own repository. I think you need to give us access to it.

**Comment by tcitworld** [comment]
Please update the readme to redirect to the other repo when it's done. :-)

**Comment by jlnostr** [comment]
So, I added you both to the collaborators. Maybe this is enough. I also tried to transfer the repository directly to the wallabag group but because I don't have admin rights, it wasn't possible to perform this step :)

**Comment by tcitworld** [comment]
Thanks, but still don't have access to your repo settings. I'll try to see on our side what we can do.

**Comment by tcitworld** [comment]
You should have access now.

**Comment by jlnostr** [comment]
Yep, it's transferring :+1:

**Comment by tcitworld** [comment]
Don't forget to rename the repos with comprehensible names. :-)

**Comment by jlnostr** [comment]
Yeah, would do it if I could access the repo settings :D
image

**Comment by tcitworld** [comment]
Oh I hate Github's permission system. Updated.

**Comment by jlnostr** [comment]
Thanks :)

**Pull request closed without merging**
