### PR TITLE
Some UI updates.

### PR DESCRIPTION
**Pull request by jlnostr**

### CODE REVIEW

**Comment by nicosomb** [comment]
Some screenshots for non windows users please? :)

**Comment by tcitworld** [comment]
Damn, 5 seconds too late.

**Comment by nicosomb** [comment]
That's why I'm your boss, guy! ;-)

**Comment by jlnostr** [comment]
Some screenshots - even if I'm not finished yet :smile: 
Main page
Single article
Adding a link

**Comment by tcitworld** [comment]
Hell yeah ! This looks really good.

**Comment by jlnostr** [comment]
Thanks!

**Pull request merged**
