### PR TITLE
add hungarian translation

### PR DESCRIPTION
**Pull request by spy14**

### CODE REVIEW

**Comment by tcitworld** [comment]
ping @jlnostr

**Comment by jlnostr** [comment]
Thanks @spy14, will update the app as fast as possible :-)

**Comment by jlnostr** [comment]
@spy14 It would be nice, if you also could translate the app description. These can be found in the following directory: `additional\app descriptions`

Thanks in advance!

**Comment by spy14** [comment]
I just sent a new pull request.

**Comment by tcitworld** [comment]
I just merged. Thank you :)

**Comment by jlnostr** [comment]
@tcitworld :+1:

**Pull request merged**
