### PR TITLE
Improve the login page

### PR DESCRIPTION
**Pull request by jlnostr**
The login page seems to be a bit confusing to some of the users. There is a simpler way of configuring wallabag, I know that. A good example is the android app of wallabag, compared to the windows version it's fairly understandable.

TODO:
- [x] Support framabag
- [x] Some UI refinements, the current one looks a bit outdated :wink:
- [x] Add links to register pages (as suggested by @tcitworld)
- [x] Add a short explanation of what wallabag is

Fixes: #1.

### CODE REVIEW

**Comment by tcitworld** [comment]
Could you add links to register pages too (framabag & v2.wallabag.org) so that the user who doesn't know what it is can create an account ?

**Comment by jlnostr** [comment]
Two questions @tcitworld:

1. Should I really add v2.wallabag.org? It might be to confusing for the average user who just created an account on framabag?
2. Has framabag already been updated to 2.x.x?

**Comment by tcitworld** [comment]
> Should I really add v2.wallabag.org? It might be to confusing for the average user who just created an account on framabag?

Well, the android app gives the choice (it added v2.wallabag.org later) : https://cloud.githubusercontent.com/assets/2197836/18310053/cb924cce-74fc-11e6-9d17-eea301992c8e.png
I think - I hope - there will be more providers in the future.

> Has framabag already been updated to 2.x.x?

No, and everyone keeps reminding me of it.  :-) :hear_no_evil:

**Comment by jlnostr** [comment]
Ah okay, thanks for the input. Will add it 😄

**Comment by jlnostr** [comment]
I think I'm finished.

<details>
<summary>Screenshots</summary>
### First page with provider selection
image

### Second page, if the provider already provides an URL
image

### Second page, if the provider doesn't provide an URL (*other*)
image

### Error message if the URL is not in a correct format (ignore the black bar)
image

### Error message if the server is not reachable
image

### Download progress
image

### Telemetry data question
image

</details>

What do you think, @wallabag/core?

**Comment by tcitworld** [comment]
Can you show the « use custom settings » panel ?

**Comment by jlnostr** [comment]
Here it is:
image

A checkbox with "Let me create the client for you" as content might be better.

**Pull request merged**
